# See documentation at
# https://github.com/rust-lang/rust/blob/master/config.toml.example

[llvm]
link-shared = true

[build]
host = ["@RUST_TARGET_TRIPLE@"]
target = ["@RUST_TARGET_TRIPLE@", "wasm32-unknown-unknown"]
docs = false
extended = true
sanitizers = false
tools = ["cargo", "src"]

[install]
prefix = "@RUST_PREFIX@"
sysconfdir = "etc"

[rust]
channel = "nightly"
optimize = true
debug = false
optimize-tests = false
codegen-tests = false
codegen-units = 0
deny-warnings = false
jemalloc = false
rpath = false

[target.x86_64-unknown-linux-gnu]
llvm-config = "@BUILD_LLVM_CONFIG@"

[target.@RUST_TARGET_TRIPLE@]
android-ndk = "@TERMUX_STANDALONE_TOOLCHAIN@"
llvm-config = "@TERMUX_PREFIX@/bin/llvm-config"
ar = "llvm-ar"
profiler = true

[dist]
src-tarball = false
missing-tools = true
