--- a/Makefile.in
+++ b/Makefile.in
@@ -5,8 +5,8 @@
 name = spnav
 lib_a = lib$(name).a

-incpaths = -I. -I/usr/local/include -I/usr/X11R6/include -I/opt/homebrew/include
-libpaths = -L/usr/local/lib -L/usr/X11R6/lib -L/opt/homebrew/lib
+incpaths = -I. -I@TERMUX_PREFIX@/include
+libpaths = -L@TERMUX_PREFIX@/lib

 CC ?= gcc
 AR ?= ar
