TERMUX_PKG_HOMEPAGE=https://github.com/mrowa44/emojify
TERMUX_PKG_DESCRIPTION="Emoji on the command line"
TERMUX_PKG_LICENSE=MIT
TERMUX_PKG_MAINTAINER=@termux
TERMUX_PKG_VERSION=2.2.0
TERMUX_PKG_SRCURL=$TERMUX_PKG_HOMEPAGE/archive/$TERMUX_PKG_VERSION.tar.gz
TERMUX_PKG_SHA256=340b866c432705989f71a61551c92af55f49f14d8f17b2c63a0db99e2d687e55
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_BUILD_IN_SRC=true
TERMUX_PKG_DEPENDS="bash"
TERMUX_PKG_PLATFORM_INDEPENDENT=true

termux_step_make_install() {
	local bin
	bin="$(basename $TERMUX_PKG_HOMEPAGE)"
	install -D "$bin" -t "$TERMUX_PREFIX/bin"
}
