TERMUX_SUBPKG_INCLUDE="
$_INSTALL_PREFIX/bin/analyze-build
$_INSTALL_PREFIX/bin/c++
$_INSTALL_PREFIX/bin/cc
$_INSTALL_PREFIX/bin/*clang*
$_INSTALL_PREFIX/bin/*cpp
$_INSTALL_PREFIX/bin/diagtool
$_INSTALL_PREFIX/bin/find-all-symbols
$_INSTALL_PREFIX/bin/*g++
$_INSTALL_PREFIX/bin/*gcc
$_INSTALL_PREFIX/bin/git-clang-format
$_INSTALL_PREFIX/bin/hmaptool
$_INSTALL_PREFIX/bin/intercept-build
$_INSTALL_PREFIX/bin/modularize
$_INSTALL_PREFIX/bin/pp-trace
$_INSTALL_PREFIX/bin/scan-*
$_INSTALL_PREFIX/include/clang*
$_INSTALL_PREFIX/include/omp*.h
$_INSTALL_PREFIX/lib/clang/*/include/*.h
$_INSTALL_PREFIX/lib/clang/*/include/*.modulemap
$_INSTALL_PREFIX/lib/clang/*/include/cuda_wrappers/
$_INSTALL_PREFIX/lib/clang/*/include/openmp_wrappers/
$_INSTALL_PREFIX/lib/clang/*/include/ppc_wrappers/
$_INSTALL_PREFIX/lib/cmake/clang
$_INSTALL_PREFIX/lib/cmake/openmp
$_INSTALL_PREFIX/lib/libclang*so
$_INSTALL_PREFIX/lib/libear/
$_INSTALL_PREFIX/lib/libomp.a
$_INSTALL_PREFIX/lib/libscanbuild/
$_INSTALL_PREFIX/libexec/
$_INSTALL_PREFIX/share/clang
$_INSTALL_PREFIX/share/man/man1/clang.1.gz
$_INSTALL_PREFIX/share/man/man1/diagtool.1.gz
$_INSTALL_PREFIX/share/man/man1/scan-*
$_INSTALL_PREFIX/share/scan-*
"
TERMUX_SUBPKG_DESCRIPTION="C language frontend for LLVM"
TERMUX_SUBPKG_DEPENDS="libcompiler-rt-15, lld-15, llvm-15, ndk-sysroot"
