TERMUX_PKG_HOMEPAGE=https://shopify.github.io/shadowenv/
TERMUX_PKG_DESCRIPTION="Reversible directory-local environment variable manipulations"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="Gouranga Das Samrat <gouranga.das.khulna@gmail.com>"
TERMUX_PKG_VERSION="3.5.2"
TERMUX_PKG_SRCURL="https://github.com/Shopify/shadowenv/archive/refs/tags/${TERMUX_PKG_VERSION}.tar.gz"
TERMUX_PKG_SHA256=a8d56444adf92264b59a37e312acdc194219ce1ab05b5277b5862bcb62f50be1
TERMUX_PKG_AUTO_UPDATE=true
TERMUX_PKG_UPDATE_METHOD=repology
TERMUX_PKG_BUILD_IN_SRC=true

termux_step_pre_configure() {
	termux_setup_rust
}

termux_step_make() {
	cargo build \
		--jobs "$TERMUX_PKG_MAKE_PROCESSES" \
		--target "$CARGO_TARGET_NAME" \
		--release
}

termux_step_make_install() {
	install -Dm700 -t "$TERMUX_PREFIX/bin" \
		"target/${CARGO_TARGET_NAME}/release/shadowenv"

	# Man pages
	install -Dm600 man/man1/shadowenv.1 \
		"$TERMUX_PREFIX/share/man/man1/shadowenv.1"
	install -Dm600 man/man5/shadowlisp.5 \
		"$TERMUX_PREFIX/share/man/man5/shadowlisp.5"

	# Shell completions (generated by build.rs into sh/completions)
	install -Dm600 sh/completions/shadowenv.bash \
		"$TERMUX_PREFIX/share/bash-completion/completions/shadowenv"
	install -Dm600 sh/completions/_shadowenv \
		"$TERMUX_PREFIX/share/zsh/site-functions/_shadowenv"
	install -Dm600 sh/completions/shadowenv.fish \
		"$TERMUX_PREFIX/share/fish/vendor_completions.d/shadowenv.fish"
	install -Dm600 sh/completions/shadowenv.elv \
		"$TERMUX_PREFIX/share/elvish/lib/shadowenv.elv"
}
