TERMUX_SUBPKG_INCLUDE="
$_INSTALL_PREFIX_R/bin/bugpoint
$_INSTALL_PREFIX_R/bin/dsymutil
$_INSTALL_PREFIX_R/bin/llc
$_INSTALL_PREFIX_R/bin/lli
$_INSTALL_PREFIX_R/bin/llvm*
$_INSTALL_PREFIX_R/bin/opt
$_INSTALL_PREFIX_R/bin/sancov
$_INSTALL_PREFIX_R/bin/sanstats
$_INSTALL_PREFIX_R/bin/split-file
$_INSTALL_PREFIX_R/bin/verify-uselistorder
$_INSTALL_PREFIX_R/share/man/man1/bugpoint.1.gz
$_INSTALL_PREFIX_R/share/man/man1/dsymutil.1.gz
$_INSTALL_PREFIX_R/share/man/man1/llc.1.gz
$_INSTALL_PREFIX_R/share/man/man1/lli.1.gz
$_INSTALL_PREFIX_R/share/man/man1/llvm*
$_INSTALL_PREFIX_R/share/man/man1/opt.1.gz
$_INSTALL_PREFIX_R/share/man/man1/*tblgen.1.gz
$_INSTALL_PREFIX_R/share/opt-viewer
"
TERMUX_SUBPKG_DESCRIPTION="LLVM modular compiler and toolchain executables"
