TERMUX_SUBPKG_DESCRIPTION="thunk-gen for host (NOT for Termux)"
TERMUX_SUBPKG_PLATFORM_INDEPENDENT=true
TERMUX_SUBPKG_DEPEND_ON_PARENT=false
TERMUX_SUBPKG_DEPENDS="python-ply"
TERMUX_SUBPKG_INCLUDE="
opt/${TERMUX_PKG_NAME}/cross/*
"
